### ISSUE TITLE
Tests failing on fresh clone

### ISSUE THREAD

**Issue by ivanbacher** [boly38/node-mongotools#95]
```
clone
npm install
npm test
```

```
▶ MTWrapper unit tests
  ✖ should wrap dump commandConnectFromOptions db user basic (1.302625ms)
    AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
        at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:31:27)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Test.start (node:internal/test_runner/test:542:17)
        at node:internal/test_runner/test:946:71
        at node:internal/per_context/primordials:488:82
        at new Promise (<anonymous>)
        at new SafePromise (node:internal/per_context/primordials:456:29)
        at node:internal/per_context/primordials:488:9
        at Array.map (<anonymous>)
        at arrayToSafePromiseIterable (node:internal/per_context/primordials:485:5)
        at node:internal/per_context/primordials:502:21
        at new Promise (<anonymous>)
        at primordials.SafePromiseAll (node:internal/per_context/primordials:501:3)
        at Suite.run (node:internal/test_runner/test:946:23)
        at async startSubtest (node:internal/test_runner/harness:216:3) {
      showDiff: true,
      actual: '--beginning --host 127.0.0.1 --port 17017 --db myDbForTest',
      expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --db myDbForTest',
      operator: 'strictEqual'
    }

  ✖ should wrap dump commandConnectFromOptions uri ssl (0.1405ms)
    AssertionError: expected '--beginning --uri mongodb://127.0.0.1…' to deeply equal '--beginning --uri mongodb://root:mypa…'
        at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:48:27)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at async Promise.all (index 0)
        at async Suite.run (node:internal/test_runner/test:948:7)
        at async startSubtest (node:internal/test_runner/harness:216:3) {
      showDiff: true,
      actual: '--beginning --uri mongodb://127.0.0.1:17017/myDbForTest --ssl --sslCAFile /tmp/myCAfile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
      expected: '--beginning --uri mongodb://root:mypass@127.0.0.1:17017/myDbForTest?authSource=admin --ssl --sslCAFile /tmp/myCAfile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
      operator: 'strictEqual'
    }

  ✖ should wrap restore commandConnectFromOptions db user basic (0.135167ms)
    AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
        at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:62:27)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
      showDiff: true,
      actual: '--beginning --host 127.0.0.1 --port 17017 --nsInclude myDbForTest.*',
      expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --nsInclude myDbForTest.*',
      operator: 'strictEqual'
    }

  ✖ should wrap restore commandConnectFromOptions db user basic source and target dbs (0.09ms)
    AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
        at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:76:27)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
      showDiff: true,
      actual: '--beginning --host 127.0.0.1 --port 17017 --nsFrom mySourceDbForTest.* --nsTo myTargetDbForTest.*',
      expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --nsFrom mySourceDbForTest.* --nsTo myTargetDbForTest.*',
      operator: 'strictEqual'
    }

  ✖ should wrap restore commandConnectFromOptions uri ssl (0.172541ms)
    AssertionError: expected '--beginning --uri mongodb://127.0.0.1…' to deeply equal '--beginning --uri mongodb://root:mypa…'
        at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:93:27)
        at Test.runInAsyncScope (node:async_hooks:206:9)
        at Test.run (node:internal/test_runner/test:631:25)
        at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
        at Test.postRun (node:internal/test_runner/test:715:19)
        at Test.run (node:internal/test_runner/test:673:12)
        at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
      showDiff: true,
      actual: '--beginning --uri mongodb://127.0.0.1:17017/myDbForTest --ssl --sslCAFile /tmp/myCAFile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
      expected: '--beginning --uri mongodb://root:mypass@127.0.0.1:17017/myDbForTest?authSource=admin --ssl --sslCAFile /tmp/myCAFile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
      operator: 'strictEqual'
    }

▶ MTWrapper unit tests (2.689625ms)



  Mongo Tools
Mongo Tools :: before
  ▶ drop test database local:27017 db:node-mongotools-test
    1) "before all" hook for "should not dump with invalid parameter"


  0 passing (17ms)
  1 failing

  1) Mongo Tools
       "before all" hook for "should not dump with invalid parameter":
     MongoServerError: Command dropDatabase requires authentication
      at Connection.sendCommand (node_modules/mongodb/lib/cmap/connection.js:281:27)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
      at async Connection.command (node_modules/mongodb/lib/cmap/connection.js:304:26)
      at async Server.command (node_modules/mongodb/lib/sdam/server.js:169:24)
      at async DropDatabaseOperation.execute (node_modules/mongodb/lib/operations/drop.js:69:9)
      at async executeOperation (node_modules/mongodb/lib/operations/execute_operation.js:105:20)
      at async dropDatabase (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/tests-utils.js:37:9)
      at async Context.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-tools.test.js:58:9)



ℹ tests 5
ℹ suites 1
ℹ pass 0
ℹ fail 5
ℹ cancelled 0
ℹ skipped 0
ℹ todo 0
ℹ duration_ms 25.541958

✖ failing tests:

test at file:/Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:22:5
✖ should wrap dump commandConnectFromOptions db user basic (1.302625ms)
  AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
      at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:31:27)
      at Test.runInAsyncScope (node:async_hooks:206:9)
      at Test.run (node:internal/test_runner/test:631:25)
      at Test.start (node:internal/test_runner/test:542:17)
      at node:internal/test_runner/test:946:71
      at node:internal/per_context/primordials:488:82
      at new Promise (<anonymous>)
      at new SafePromise (node:internal/per_context/primordials:456:29)
      at node:internal/per_context/primordials:488:9
      at Array.map (<anonymous>)
      at arrayToSafePromiseIterable (node:internal/per_context/primordials:485:5)
      at node:internal/per_context/primordials:502:21
      at new Promise (<anonymous>)
      at primordials.SafePromiseAll (node:internal/per_context/primordials:501:3)
      at Suite.run (node:internal/test_runner/test:946:23)
      at async startSubtest (node:internal/test_runner/harness:216:3) {
    showDiff: true,
    actual: '--beginning --host 127.0.0.1 --port 17017 --db myDbForTest',
    expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --db myDbForTest',
    operator: 'strictEqual'
  }

test at file:/Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:34:5
✖ should wrap dump commandConnectFromOptions uri ssl (0.1405ms)
  AssertionError: expected '--beginning --uri mongodb://127.0.0.1…' to deeply equal '--beginning --uri mongodb://root:mypa…'
      at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:48:27)
      at Test.runInAsyncScope (node:async_hooks:206:9)
      at Test.run (node:internal/test_runner/test:631:25)
      at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
      at Test.postRun (node:internal/test_runner/test:715:19)
      at Test.run (node:internal/test_runner/test:673:12)
      at async Promise.all (index 0)
      at async Suite.run (node:internal/test_runner/test:948:7)
      at async startSubtest (node:internal/test_runner/harness:216:3) {
    showDiff: true,
    actual: '--beginning --uri mongodb://127.0.0.1:17017/myDbForTest --ssl --sslCAFile /tmp/myCAfile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
    expected: '--beginning --uri mongodb://root:mypass@127.0.0.1:17017/myDbForTest?authSource=admin --ssl --sslCAFile /tmp/myCAfile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
    operator: 'strictEqual'
  }

test at file:/Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:53:5
✖ should wrap restore commandConnectFromOptions db user basic (0.135167ms)
  AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
      at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:62:27)
      at Test.runInAsyncScope (node:async_hooks:206:9)
      at Test.run (node:internal/test_runner/test:631:25)
      at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
      at Test.postRun (node:internal/test_runner/test:715:19)
      at Test.run (node:internal/test_runner/test:673:12)
      at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
    showDiff: true,
    actual: '--beginning --host 127.0.0.1 --port 17017 --nsInclude myDbForTest.*',
    expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --nsInclude myDbForTest.*',
    operator: 'strictEqual'
  }

test at file:/Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:65:5
✖ should wrap restore commandConnectFromOptions db user basic source and target dbs (0.09ms)
  AssertionError: expected '--beginning --host 127.0.0.1 --port 1…' to deeply equal '--beginning --host 127.0.0.1 --port 1…'
      at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:76:27)
      at Test.runInAsyncScope (node:async_hooks:206:9)
      at Test.run (node:internal/test_runner/test:631:25)
      at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
      at Test.postRun (node:internal/test_runner/test:715:19)
      at Test.run (node:internal/test_runner/test:673:12)
      at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
    showDiff: true,
    actual: '--beginning --host 127.0.0.1 --port 17017 --nsFrom mySourceDbForTest.* --nsTo myTargetDbForTest.*',
    expected: '--beginning --host 127.0.0.1 --port 17017 --username root --password mypass --authenticationDatabase admin --nsFrom mySourceDbForTest.* --nsTo myTargetDbForTest.*',
    operator: 'strictEqual'
  }

test at file:/Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:79:5
✖ should wrap restore commandConnectFromOptions uri ssl (0.172541ms)
  AssertionError: expected '--beginning --uri mongodb://127.0.0.1…' to deeply equal '--beginning --uri mongodb://root:mypa…'
      at TestContext.<anonymous> (file:///Users/ivan/Workspace/Forks/node-mongotools/tests/mongo-wrapper-unit.test.js:93:27)
      at Test.runInAsyncScope (node:async_hooks:206:9)
      at Test.run (node:internal/test_runner/test:631:25)
      at Suite.processPendingSubtests (node:internal/test_runner/test:374:18)
      at Test.postRun (node:internal/test_runner/test:715:19)
      at Test.run (node:internal/test_runner/test:673:12)
      at async Suite.processPendingSubtests (node:internal/test_runner/test:374:7) {
    showDiff: true,
    actual: '--beginning --uri mongodb://127.0.0.1:17017/myDbForTest --ssl --sslCAFile /tmp/myCAFile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
    expected: '--beginning --uri mongodb://root:mypass@127.0.0.1:17017/myDbForTest?authSource=admin --ssl --sslCAFile /tmp/myCAFile --sslPEMKeyFile /tmp/pem/sslPEMKeyFile --sslPEMKeyPassword strongPassHere --sslCRLFile /tmp/pem/sslCRLFile --sslFIPSMode --tlsInsecure',
    operator: 'strictEqual'
  }
```

**Comment by boly38** [comment]
hi @ivanbacher 
thanks for your question
it's true that test require some env variables, like in `initEnv.test.sh` and this is maybe not well explained (to be improved for sure).

but what you need to know is that test context [beginning of the test file](https://github.com/boly38/node-mongotools/blob/main/tests/mongo-tools.test.js#L20-L27) must match a mongo server instance

**Comment by ivanbacher** [comment]
Hi @boly38. Of course, how could I have missed that 🤯. Thanks for the info. I'll take a better look next time.
