### ISSUE TITLE
Error while file upload to dropbox

### ISSUE THREAD

**Issue by ugeshgupta000** [boly38/node-mongotools#97]
I am trying to use node-mongotools package with dropbox upload. I have set the relevant tokens for getting long lived token, but i get below error:

```

uploadErr TypeError: _this3.fetch is not a function
    at <unknown> (turbopack://[project]/node_modules/dropbox/es/src/dropbox.js:160:22)
  158 |         return fetchOptions;
  159 |       }).then(function (fetchOptions) {
> 160 |         return _this3.fetch(baseApiUrl(host, _this3.domain, _this3.domainDelimiter) + path, fetchOptions);
      |                      ^
  161 |       }).then(function (res) {
  162 |         return parseResponse(res);
  163 |       });
```

Code snippet:

```

var mongoTools = new MongoTools();
const mtOptions = {
    uri: getDbUri(''), // Empty to take backup for all databases.
    // dropboxToken: process.env.DROPBOX_TOKEN,
    dropboxAppKey: process.env.DROPBOX_APIKEY,
    dropboxAppSecret: process.env.DROPBOX_APISECRET,
    dropboxRefreshToken: process.env.DROPBOX_REFRESHTOKEN,
    path: 'data/backups'
};

export const createMongoDbDump = async () => {
    // mongoTools.list(mtOptions).then((x: any) => console.log(x));

    const result = await mongoTools
        .mongodump(mtOptions)
        .catch((err: any) => console.error("Mongodb backup job error =>", err));
    console.log(result);

    // We may delete the backup file which is created in backup folder on FS.
    // For now, keeping it as is, since storage might not be a problem currently.
}
```

**Comment by boly38** [comment]
arg, I'm unable to reproduce on my side by playing locally test
it seems to be dropbox internal lib issue (wrong handling of negative usecase)

- adding `MT_DROPBOX_DEBUG=true` could provide you a little bit more context. but that wont fix.

It's maybe related to dropbox token .. and you could play with boly38/dropbox-refresh-token and especially with `launch step by step to get refreshToken` to double-check your environment values.

I keep interested to help you with this issue to improve current repository, let me know about updates or if you found more precise way to reproduce
cheers

**Comment by boly38** [comment]
after cloning repo locally, 
I just play with this extra file `simpleUploadTest.js` (that isolate dropbox upload/list feature only)
and I have no issue on my side :| 

````
import MongoTools from "../../lib/MongoTools.js";
import MTOptions from "../../lib/MTOptions.js";

const options = new MTOptions()
const mt = new MongoTools();

const list = () => {
    mt.dbx.listFromDropbox(options)
        .then(console.log)
        .catch(console.error)
}

const upload = () => {
    // generate  10MB file (linux) : dd if=/dev/zero of=/WORK/node-mongotools/output.dat  bs=1024  count=10240
    // generate 148MB file (linux) : dd if=/dev/zero of=/WORK/node-mongotools/output.dat  bs=1024  count=151240
    // generate 156MB file (linux) : dd if=/dev/zero of=/WORK/node-mongotools/output.dat  bs=1024  count=159240
    mt.dbx.mongoDumpUploadOnDropbox(options, {"fullFileName":"./output.dat"})
}

const firstArg = process.argv[2];
if (firstArg === "list")
    list();
else if (firstArg === "options")
    console.log(options);
else if (firstArg === "upload")
    upload(); // think to remove it before new test
else
    console.log("??")
````

example of use
````
MT_DROPBOX_DEBUG=true node simpleUploadTest.js upload
````

**Comment by ugeshgupta000** [comment]
First of all, sorry it took quite some time to get back. Apologies for that.

So i checked the refresh utility, and if i set the same appKey, secret and refreshToken there, then it determines the credentials as successful.
<img width="1069" alt="image" src="https://github.com/user-attachments/assets/dcf0f60c-65f1-4b75-ab74-ce43d9c11cb8">

However, if i am using the same credentials with node-mongotools, it throws this error:
```

isValid:false error:invalid_access_token/ - so dropboxRefreshAccessToken
Dropbox upload /data/backups/all__2024-11-30_022545.gz:
uploadErr TypeError: _this3.fetch is not a function
    at <unknown> (turbopack://[project]/node_modules/dropbox/es/src/dropbox.js:160:22)
  158 |         return fetchOptions;
  159 |       }).then(function (fetchOptions) {
> 160 |         return _this3.fetch(baseApiUrl(host, _this3.domain, _this3.domainDelimiter) + path, fetchOptions);
      |                      ^
  161 |       }).then(function (res) {
  162 |         return parseResponse(res);
  163 |       });
Mongodb backup job error => Error: Dropbox upload /data/backups/all__2024-11-30_022545.gz: [status:undefined] undefined
    at <unknown> (turbopack://[project]/node_modules/node-mongotools/lib/MTDropbox.js:64:39)
  62 |                                 const {status, error} = uploadErr;
  63 |                                 const errorMessage = `Dropbox upload ${dbxFilename}: [status:${status}] ${error?.error_summary}`;
> 64 |                                 reject(new Error(errorMessage));
     |                                       ^
  65 |                             });
  66 |                     });
  67 |                 })
undefined

```

**Comment by boly38** [comment]
FYI / I tried with extra exploratory tests on `Dropbox({"accessToken` value
- extra bad char but supported : got 401 from dbx as expected
- extra bad char not supported as header (ex. \n \x01) : got `is not a legal HTTP header value` from `node-fetch` (make sense)

unfortunately, I'm unable to reproduce exactly this dbx issue. 
If someone get an howto reproduce, please append this issue here 🙏
